name: Generate and Run C++ Experiments

on: [push]

jobs:
  build-run-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2 # Installe la bibliothèque Jinja2 requise

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest

    - name: Run Python script to generate, compile, and execute C++
      run: python generate.py
      working-directory: ./template-based 

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit results.csv
      run: |
        git add analyze/results.csv
        # Commit only if there are changes staged
        git diff --staged --quiet || git commit -m "docs: update results.csv from automated experiment run [skip ci]"

    - name: Pull latest changes with rebase
      run: |
        git pull --rebase origin ${{ github.ref_name }}

    - name: Push changes
      run: |
        git push origin ${{ github.ref_name }}

